apps/platillos/urls.py
from django.urls import path
from . import views

app_name = 'platillos'

urlpatterns = [    
    path('categorias/', views.CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/add/', views.CategoriaCreateView.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/edit/', views.CategoriaUpdateView.as_view(), name='categoria_edit'),
    path('categorias/<int:pk>/delete/', views.CategoriaDeleteView.as_view(), name='categoria_delete'),
    path('platillos/', views.PlatilloListView.as_view(), name='platillos_list'),
    path('platillos/add/', views.PlatilloCreateView.as_view(), name='platillos_create'),
    path ('platillos/<int:pk>/edit/', views.PlatilloUpdateView.as_view(), name='platillos_edit'),
    path ('platillos/<int:pk>/delete/', views.PlatilloDeleteView.as_view(), name='platillos_delete'),
]

restaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_index, name='main_index'),
    path('accounts/', include('apps.accounts.urls')),
    path('platillos/', include('apps.platillos.urls')),
    path('dashboard/', views.index_user, name='index_user'),
    path('mesas/', include('apps.mesas.urls')),
    path('ordenes/', include('apps.mesas.urls')),
    path('api/', include('apps.api.urls')),
]

templates/categorias/categoria_confirm_delete.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Eliminar categoría</h1>

<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar la categoría? "{{ object.nombre }}"?</p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a class= "btn btn-primary" href="{% url 'platillos:categoria_list' %}" class="btn btn-secondary">Regresar</a>
</form>
{% endblock %}

templates/categorias/categoria_edit_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Editar categoría</h1>

<form action="{% url 'platillos:categoria_edit' form.instance.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/categorias/categoria_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar Categoría</h1>

<form action="{% url 'platillos:categoria_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/categorias/categoria_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de Categorias</h1>
<a class="btn btn-primary" href="{% url 'platillos:categoria_create' %}">Agregar categoría</a>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        {% for categoria in categorias %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'platillos:categoria_edit' categoria.pk %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'platillos:categoria_delete' categoria.pk %}">Eliminar</a>
            </td>
            <td>{{categoria.nombre}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}