apps/mesas/urls.py
from django.urls import path
from . import views

app_name = 'mesas'

urlpatterns = [  
    path('mesas_estado/', views.MesasEstadoListView.as_view(), name='mesas_estado_list'),
    path('mesas_estado/add/', views.MesasEstadoCreateView.as_view(), name='mesas_estado_create'),
    path('mesas_estado/<int:pk>/edit/', views.MesasEstadoUpdateView.as_view(), name='mesas_estado_edit'),
    path('mesas_estado/<int:pk>/delete/', views.MesasEstadoDeleteView.as_view(), name='mesas_estado_delete'),
      
    path('mesas/', views.MesaListView.as_view(), name='mesas_list'),
    path('mesas/add/', views.MesaCreateView.as_view(), name='mesas_create'),
    path('mesas/<int:pk>/edit/', views.MesaUpdateView.as_view(), name='mesas_edit'),
    path('mesas/<int:pk>/delete/', views.MesaDeleteView.as_view(), name='mesas_delete'),
    
    path('ordenes/', views.OrdenListView.as_view(), name='ordenes_list'),
    path('ordenes/add/', views.OrdenCreateView.as_view(), name='ordenes_create'),
    
    path('ordenes/<int:orden_id>/detalles/', views.OrdenDetalleView.as_view(), name='ordenes_detalle_list'),
    path('ordenes/<int:pk>/detalles/edit/', views.OrdenDetalleUpdateView.as_view(), name='ordenes_detalle_update'),
    path('ordenes/detalles/eliminar/<int:pk>/', views.OrdenDetalleDeleteView.as_view(), name='ordenes_detalle_delete'),
    
    path('ordenes/<int:orden_id>/pagar', views.OrdenPagarView.as_view(), name='ordenes_pagar'),
    
    path('metodos_pago/', views.MetodoPagoListView.as_view(), name='metodos_pago_list'),
    path('metodos_pago/add/', views.MetodoPagoCreateView.as_view(), name='metodos_pago_create'),
    path('metodos_pago/<int:pk>/edit/', views.MetodoPagoUpdateView.as_view(), name='metodos_pago_edit'),
    path('metodos_pago/<int:pk>/delete/', views.MetodoPagoDeleteView.as_view(), name='metodos_pago_delete'),
    
    path('pagos/', views.PagoListView.as_view(), name='pagos_list'),
]

restaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_index, name='main_index'),
    path('accounts/', include('apps.accounts.urls')),
    path('platillos/', include('apps.platillos.urls')),
    path('dashboard/', views.index_user, name='index_user'),
    path('mesas/', include('apps.mesas.urls')),
    path('ordenes/', include('apps.mesas.urls')),
    path('api/', include('apps.api.urls')),
]

templates/ordenes/ordenes_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar Orden</h1>

<form action="{% url 'mesas:ordenes_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/ordenes/ordenes_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de Ordenes</h1>
<a class="btn btn-primary" href="{% url 'mesas:ordenes_create' %}">Agregar Orden</a>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Fecha</th>
            <th>Mesa</th>
            <th>Total</th>
            <th>Estatus</th>
        </tr>
    </thead>
    <tbody>
        {% for orden in ordenes %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'mesas:ordenes_detalle_list' orden.pk %}">Editar</a>
                <a class="btn btn-success" href="{% url 'mesas:ordenes_pagar' orden.pk %}">Pagar</a>
            </td>
            <td>{{orden.fecha_hora}}</td>
            <td>{{orden.mesa.nombre}}</td>
            <td>{{orden.total}}</td>
            <td>{{orden.estatus}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/ordenes/ordenes_pagar.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Pagar Orden No. {{ orden.id }} - {{ orden.fecha_hora }}</h1>

<table class="table">
    <thead>
        <tr>
            <th>Platillo</th>
            <th>Cantidad</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for detalle in detalles %}
        <tr>            
            <td>{{detalle.platillo.nombre}}</td>
            <td>{{detalle.cantidad}}</td> 
            <td>{{detalle.subtotal}}</td>           
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>Total: {{total}}</h2>

<form action="{% url 'mesas:ordenes_pagar' orden.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Pagar</button>
    <a href="{% url 'mesas:ordenes_list' %}" class="btn btn-secondary">Regresar</a>
</form>

{% endblock %}