apps/mesas/urls.py
from django.urls import path
from . import views

app_name = 'mesas'

urlpatterns = [  
    path('mesas_estado/', views.MesasEstadoListView.as_view(), name='mesas_estado_list'),
    path('mesas_estado/add/', views.MesasEstadoCreateView.as_view(), name='mesas_estado_create'),
    path('mesas_estado/<int:pk>/edit/', views.MesasEstadoUpdateView.as_view(), name='mesas_estado_edit'),
    path('mesas_estado/<int:pk>/delete/', views.MesasEstadoDeleteView.as_view(), name='mesas_estado_delete'),
      
    path('mesas/', views.MesaListView.as_view(), name='mesas_list'),
    path('mesas/add/', views.MesaCreateView.as_view(), name='mesas_create'),
    path('mesas/<int:pk>/edit/', views.MesaUpdateView.as_view(), name='mesas_edit'),
    path('mesas/<int:pk>/delete/', views.MesaDeleteView.as_view(), name='mesas_delete'),
    
    path('ordenes/', views.OrdenListView.as_view(), name='ordenes_list'),
    path('ordenes/add/', views.OrdenCreateView.as_view(), name='ordenes_create'),
    
    path('ordenes/<int:orden_id>/detalles/', views.OrdenDetalleView.as_view(), name='ordenes_detalle_list'),
    path('ordenes/<int:pk>/detalles/edit/', views.OrdenDetalleUpdateView.as_view(), name='ordenes_detalle_update'),
    path('ordenes/detalles/eliminar/<int:pk>/', views.OrdenDetalleDeleteView.as_view(), name='ordenes_detalle_delete'),
    
    path('ordenes/<int:orden_id>/pagar', views.OrdenPagarView.as_view(), name='ordenes_pagar'),
    
    path('metodos_pago/', views.MetodoPagoListView.as_view(), name='metodos_pago_list'),
    path('metodos_pago/add/', views.MetodoPagoCreateView.as_view(), name='metodos_pago_create'),
    path('metodos_pago/<int:pk>/edit/', views.MetodoPagoUpdateView.as_view(), name='metodos_pago_edit'),
    path('metodos_pago/<int:pk>/delete/', views.MetodoPagoDeleteView.as_view(), name='metodos_pago_delete'),
    
    path('pagos/', views.PagoListView.as_view(), name='pagos_list'),
]

restaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_index, name='main_index'),
    path('accounts/', include('apps.accounts.urls')),
    path('platillos/', include('apps.platillos.urls')),
    path('dashboard/', views.index_user, name='index_user'),
    path('mesas/', include('apps.mesas.urls')),
    path('ordenes/', include('apps.mesas.urls')),
    path('api/', include('apps.api.urls')),
]

templates/metodos_pagos/metodos_pago_confirm_delete.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Eliminar Metodo de Pago</h1>

<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar este metodo de pago? "{{ object.nombre }}"?</p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a class= "btn btn-primary" href="{% url 'mesas:metodos_pago_list' %}" class="btn btn-secondary">Regresar</a>
</form>
</form>
{% endblock %}

templates/metodos_pagos/metodos_pago_edit_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Editar Metodos de Pago</h1>

<form action="{% url 'mesas:metodos_pago_edit' form.instance.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/metodos_pagos/metodos_pago_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar Metodos de Pago</h1>

<form action="{% url 'mesas:metodos_pago_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/metodos_pagos/metodos_pago_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de Metodos de Pago</h1>
<a class="btn btn-primary" href="{% url 'mesas:metodos_pago_create' %}">Agregar Metodo de pago</a>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        {% for metodos_pago in object_list %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'mesas:metodos_pago_edit' metodos_pago.pk %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'mesas:metodos_pago_delete' metodos_pago.pk %}">Eliminar</a>
            </td>
            <td>{{metodos_pago.nombre}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}